version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: auth_manager_db
    environment:
      POSTGRES_USER: auth_manager_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: auth_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_manager_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_manager_user -d auth_manager_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_manager_svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_manager_svc
    environment:
      DB_USER: auth_manager_user
      DB_PASSWORD: supersecretpassword
      DB_NAME: auth_manager_db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DSN: postgres://auth_manager_user:supersecretpassword@postgres:5432/auth_manager_db?sslmode=disable
      JWT_SECRET: "secretkey"
      REFRESH_TOKEN_SECRET: "refresh-secret-key"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_manager_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  auth_manager_network:
    driver: bridge